# Generated by `make depfile`. Do not edit by hand.

$(BUILD_DIR)/obj/src/main.o: \
	$(BUILD_DIR)/generated/build_info.h \
	$(ROOT_DIR)/src/main.c
$(BUILD_DIR)/obj/src/util/error.o: \
	$(ROOT_DIR)/src/util/error.c \
	$(ROOT_DIR)/src/util/error.h
$(BUILD_DIR)/obj/src/util/file.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/file.c \
	$(ROOT_DIR)/src/util/file.h \
	$(ROOT_DIR)/src/util/string.h
$(BUILD_DIR)/obj/src/util/path.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/path.c \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h
$(BUILD_DIR)/obj/src/util/string.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/string.c \
	$(ROOT_DIR)/src/util/string.h
$(BUILD_DIR)/obj/src/util/time.o: \
	$(ROOT_DIR)/src/util/error.h \
	$(ROOT_DIR)/src/util/time.c \
	$(ROOT_DIR)/src/util/time.h
$(BUILD_DIR)/obj/test-bin/runner/environment.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/runner/environment.c
$(BUILD_DIR)/obj/test-bin/runner/error.c.bin: \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/error.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/runner/error.c
$(BUILD_DIR)/obj/test-bin/runner/markers.c.bin: \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/runner/markers.c
$(BUILD_DIR)/obj/test-bin/runner/no-subtests.c.bin: \
	$(ROOT_DIR)/testing/tests/runner/no-subtests.c
$(BUILD_DIR)/obj/test-bin/runner/output.c.bin: \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/runner/output.c
$(BUILD_DIR)/obj/test-bin/runner/spaced-subtests.c.bin: \
	$(ROOT_DIR)/testing/tests/runner/spaced-subtests.c
$(BUILD_DIR)/obj/test-bin/unit/util/array.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/array.c
$(BUILD_DIR)/obj/test-bin/unit/util/file.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/file.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/file.c
$(BUILD_DIR)/obj/test-bin/unit/util/path.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/path.c
$(BUILD_DIR)/obj/test-bin/unit/util/string.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/string.c
$(BUILD_DIR)/obj/test-bin/unit/util/time-sleep.c.bin: \
	$(ROOT_DIR)/src/util/time.h \
	$(ROOT_DIR)/testing/tests/unit/util/time-sleep.c
$(BUILD_DIR)/obj/test-bin/unit/util/time.c.bin: \
	$(ROOT_DIR)/src/util/time.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/time.c
$(BUILD_DIR)/obj/testing/support/test_main.o: \
	$(ROOT_DIR)/testing/support/test_main.c \
	$(ROOT_DIR)/testing/support/test_main.h
$(BUILD_DIR)/obj/testing/tools/run-and-check.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/error.h \
	$(ROOT_DIR)/src/util/file.h \
	$(ROOT_DIR)/src/util/klib/khash.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/tools/run-and-check.c
$(BUILD_DIR)/obj/testing/tools/test-runner.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/error.h \
	$(ROOT_DIR)/src/util/file.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/src/util/time.h \
	$(ROOT_DIR)/testing/tools/test-runner.c
