# Generated by `make depfile`. Do not edit by hand.

$(BUILD_DIR)/obj/src/main.o: \
	$(BUILD_DIR)/generated/build_info.h \
	$(ROOT_DIR)/src/main.c
$(BUILD_DIR)/obj/src/util/path.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/path.c \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h
$(BUILD_DIR)/obj/test-bin/runner/environment.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/runner/environment.c
$(BUILD_DIR)/obj/test-bin/runner/output.c.bin: \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/runner/output.c
$(BUILD_DIR)/obj/test-bin/unit/util/array.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/array.c
$(BUILD_DIR)/obj/test-bin/unit/util/path.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/path.c
$(BUILD_DIR)/obj/test-bin/unit/util/string.c.bin: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test_main.h \
	$(ROOT_DIR)/testing/tests/unit/util/string.c
$(BUILD_DIR)/obj/testing/support/test-runner.o: \
	$(ROOT_DIR)/src/util/array.h \
	$(ROOT_DIR)/src/util/path.h \
	$(ROOT_DIR)/src/util/string.h \
	$(ROOT_DIR)/testing/support/test-runner.c
$(BUILD_DIR)/obj/testing/support/test_main.o: \
	$(ROOT_DIR)/src/util/common.h \
	$(ROOT_DIR)/testing/support/test_main.c \
	$(ROOT_DIR)/testing/support/test_main.h
