#!/bin/sh

# Normalize compiler-generated depfiles into one checked-in Makefile fragment
# that uses repository and build variables instead of absolute paths.

set -eu

if [ "$#" -ne 4 ]; then
    printf '%s\n' "usage: $0 ROOT_DIR BUILD_DIR OBJ_DIR OUTPUT" >&2
    exit 1
fi

ROOT_DIR=$1
BUILD_DIR=$2
OBJ_DIR=$3
OUTPUT=$4

TMP_RULES=$(mktemp)
TMP_OUTPUT=$(mktemp)

cleanup() {
    rm -f "$TMP_RULES" "$TMP_OUTPUT"
}

trap cleanup EXIT HUP INT TERM

if [ ! -d "$OBJ_DIR" ]; then
    printf '%s\n' "error: missing object directory: $OBJ_DIR" >&2
    exit 1
fi

LC_ALL=C find "$OBJ_DIR" -type f -name '*.d' -exec \
awk -v root_dir="$ROOT_DIR" -v build_dir="$BUILD_DIR" '

# Return text with leading and trailing whitespace removed.
function trim(text) {
    # sub() edits its string argument in place.
    sub(/^[[:space:]]+/, "", text)
    sub(/[[:space:]]+$/, "", text)
    return text
}

# Sort values[1..count] in place with insertion sort. This is used to sort lists
# of prerequisites, which are typically short.
# i, j, tmp are scratch variables.
function sort_strings(values, count, i, j, tmp) {
    for (i = 2; i <= count; ++i) {
        tmp = values[i]
        j = i - 1
        while (j >= 1 && values[j] > tmp) {
            values[j + 1] = values[j]
            --j
        }
        values[j + 1] = tmp
    }
}

# Rewrite an absolute or repo-relative path to use $(BUILD_DIR) or $(ROOT_DIR)
# in the final depfile, leaving unrelated paths untouched.
function normalize_path(path) {
    path = trim(path)
    if (path == "")
        return ""

    if (substr(path, 1, 1) != "/")
        path = root_dir "/" path

    # index(s, prefix) == 1 is awk’s direct “starts with” test.
    if (index(path, build_dir "/") == 1)
        return "$(BUILD_DIR)/" substr(path, length(build_dir) + 2)
    if (index(path, root_dir "/") == 1)
        return "$(ROOT_DIR)/" substr(path, length(root_dir) + 2)

    return path
}

# Normalize the accumulated raw `rule_text`, deduplicate and sort its
# prerequisites, and print a single-line "target: prereq..." record.
# All the arguments are scratch variables.
function flush_rule(raw, colon, target, prereq_text, prereq_count, i, count, prereq) {
    raw = trim(rule_text)
    rule_text = ""
    if (raw == "")
        return

    colon = index(raw, ":")
    if (colon == 0)
        return

    target = normalize_path(substr(raw, 1, colon - 1))
    prereq_text = trim(substr(raw, colon + 1))
    if (prereq_text == "")
        return

    gsub(/[[:space:]]+/, " ", prereq_text)

    # seen_prereq tracks which prerequisites we have already emitted for this
    # rule. Clear it before use.
    delete seen_prereq
    prereq_count = 0
    # split() returns the number of fields written into raw_prereqs[].
    count = split(prereq_text, raw_prereqs, " ")
    for (i = 1; i <= count; ++i) {
        prereq = normalize_path(raw_prereqs[i])
        if (prereq == "" || seen_prereq[prereq])
            continue
        seen_prereq[prereq] = 1
        prereqs[++prereq_count] = prereq
    }

    if (prereq_count == 0)
        return

    sort_strings(prereqs, prereq_count)
    printf "%s:", target
    for (i = 1; i <= prereq_count; ++i)
        printf " %s", prereqs[i]
    printf "\n"
}

{
    # GCC/Clang depfiles may span multiple physical lines with trailing
    # backslashes, so accumulate them until the logical rule is complete.
    line = $0
    sub(/[[:space:]]+$/, "", line)
    if (line == "")
        next

    # sub(/\\$/, "", line) both strips a trailing continuation backslash and
    # returns 1 when one was present, 0 otherwise.
    continued = sub(/\\$/, "", line)
    line = trim(line)
    if (rule_text != "")
        rule_text = rule_text " " line
    else
        rule_text = line

    if (!continued)
        flush_rule()
}

END {
    flush_rule()
}
' {} + | LC_ALL=C sort -u >"$TMP_RULES"

mkdir -p "$(dirname "$OUTPUT")"
{
    printf '%s\n' '# Generated by `make depfile`. Do not edit by hand.'
    printf '%s\n' ''
    # REVIEW: Just do it in the main awk script above
    awk '
    {
        # Reformat the normalized single-line rules into one prerequisite per
        # line so diffs stay readable when a dependency is added or removed.
        # With the default field splitting, $1 is the target token and $2..$NF
        # are its prerequisites from the single-line normalized rule.
        target = $1
        sub(/:$/, "", target)

        printf "%s: \\\n", target
        for (i = 2; i <= NF; ++i) {
            if (i < NF)
                printf "\t%s \\\n", $i
            else
                printf "\t%s\n", $i
        }
    }
    ' "$TMP_RULES"
} >"$TMP_OUTPUT"

mv "$TMP_OUTPUT" "$OUTPUT"
